In [1]:
!pip install nltk

In [1]:
import numpy as np
import pandas as pd
import nltk
import re 
from nltk import tokenize
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from scipy import sparse

nltk.download('punkt_tab')
nltk.download('stopwords')# Download the 'punkt' resource
nltk.download('wordnet') # Download the 'wordnet' resource 

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\rithv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rithv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rithv\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [2]:
print(nltk.data.path)

['C:\\Users\\rithv/nltk_data', 'D:\\GMU Courses\\CS-584\\Assignments\\HW1\\myenv\\nltk_data', 'D:\\GMU Courses\\CS-584\\Assignments\\HW1\\myenv\\share\\nltk_data', 'D:\\GMU Courses\\CS-584\\Assignments\\HW1\\myenv\\lib\\nltk_data', 'C:\\Users\\rithv\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']


In [3]:
#data = pd.read_csv("Train.txt", delimiter="EOF", on_bad_lines='skip')

file = "Train.txt"

In [4]:
with open("Train.txt") as f:
    for _ in range(10):
        print(f.readline())

+1	One of my all-time favorite so-laughably-lousy-that-it's-totally-lovable el cheapo and stinko nickel'n'dime independent horror creature features, an enjoyably dreadful marvel that was released by the formidably fecund exploitation outfit Crown International Pictures so it could play numerous crappy double bills at countless drive-ins back in the 70's and eventually wound up being rerun like crazy on several small-time secondary cable stations throughout the 80's. I naturally first saw this gloriously ghastly abomination on late-night television one fateful Saturday evening while in my early teens and have had a deep-seated, albeit completely irrational abiding fondness for it ever since.<br /><br />A meteorite falls out of the sky and crashes into the still waters of a tranquil country lake, thereby causing a heretofore dormant dinosaur egg to hatch. Of course, the baby dino immediately grows into a gigantic waddling, grunting, teeth-gnashing prehistoric behemoth with goofy flippers

In [5]:
stop_words = set(stopwords.words('english'))
unwanted_words = {"br"} 

def preprocess_text(text):
    # Remove HTML tags like <br> and other unwanted characters
    text = re.sub(r'<br\s*/?>', ' ', text)
    text = text.lower()  # Convert text to lowercase for uniformity
    text = re.sub(r"[^a-zA-Z0-9\s']", '', text)  # Remove punctuation

    # Tokenize the text
    word_tokens = word_tokenize(text)

    # Lemmatizer to reduce words to their base form
    lemmatizer = WordNetLemmatizer()

    # Filter out stopwords and unwanted words, and lemmatize the remaining words
    lemmas = [lemmatizer.lemmatize(word) for word in word_tokens if word not in stop_words and word not in unwanted_words]

    return ' '.join(lemmas) 

In [6]:
def process_reviews_from_file(file):
    preprocessed_data = []
    
    with open(file, 'r', encoding='utf-8') as file:
        for line in file:
            if line.strip():  # Skip empty lines
                # The label is at the beginning (+1 or -1), followed by the review text
                label = int(line[0:2].strip())

                # Replace the label -1 with 2 ( This is done because bincount doesn't accecpts negative characters )
                if label == -1:
                    label = 2

                review = line[2:].strip()

                # Removing "EOF" at the end of each para 
                if review.endswith("EOF"):
                    review = review[:-3].strip()  
                review_text = preprocess_text(review)

                # Append the result in the desired format
                preprocessed_data.append([review_text, label])
    return preprocessed_data


In [7]:
data = process_reviews_from_file(file)

In [8]:
data[5]

["thing come indeed classic work speculative fiction essay destructive nature war terror progress make surprising accurate depiction war follow year later woefully naive 's utopian ideal raymond massey cedric hardwicke ralph richardson make fine cast although drama played stage piece work cinema grandiose somewhat stilted speech often delivered actor trying reach back theater however profound word technology savior mankind instrument destruction film visual feast one detach oneself age effect sure hollywood sophisticated today rarely inventive imaginative third act treat world underground city massive deco bomber space cannon gyro copters secret organization scientist savior making scifi pulp adventure instead us trapping philosophical exercise thing come metropolis hallmark neolithic hollywood science fiction cinema operatic scope visually inspiring technology long left behind idea still burst forth artistry one heart emotion computer generated massproduced cinema today film product a

In [9]:
labels = [item[1] for item in data]
print("Negative labels:", [label for label in labels if label < 0])

Negative labels: []


In [10]:
# def remove_eof(data):
#     for item in data:  # Iterate over each dictionary in the list
#         if 'reviews' in item:  # Check if 'reviews' key exists
#             if isinstance(item['reviews'], list):
#                 # Join list into a single string
#                 item['reviews'] = ' '.join(item['reviews'])
#             item['reviews'] = item['reviews'].replace(' eof', '')   # Remove "eof" with a preceding space for safety

# # Call the function
# remove_eof(data)   
# data[2]

In [11]:
# df = pd.DataFrame(data)
# df.head()

In [12]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
X_train = tfidf_vectorizer.fit_transform([df[0] for df in data])
Y_train = [df[1] for df in data]

In [14]:
#len(X_train)

In [15]:
dense_X = X_train
non_zero_elements = dense_X[0][dense_X[0] != 0]  # Access row and filter

In [16]:
non_zero_elements = dense_X[0][dense_X[0] != 0]  # Filters the first row for non-zero elements.
print(non_zero_elements)

[[0.03872687 0.03717451 0.06489936 0.05807961 0.05586876 0.05271872
  0.02037524 0.04876381 0.04565178 0.08004175 0.0512202  0.0461312
  0.03821737 0.0512202  0.05599855 0.04094828 0.06574032 0.03707612
  0.06967116 0.0489781  0.03846078 0.07774554 0.07327881 0.02150423
  0.04461285 0.0459806  0.07327881 0.07774554 0.04664127 0.06833777
  0.06897666 0.08327809 0.04480366 0.06043263 0.03346181 0.16008351
  0.04636257 0.0243556  0.05174013 0.03649858 0.0168661  0.04977695
  0.04010136 0.06668044 0.08327809 0.08327809 0.08004175 0.05513145
  0.06114789 0.06489936 0.02158455 0.07248253 0.04418461 0.04331095
  0.02971617 0.0514389  0.03917514 0.05307352 0.05298333 0.04977695
  0.0348505  0.02746872 0.04835176 0.0461693  0.04583278 0.03814717
  0.04100807 0.0489781  0.04110872 0.05791156 0.03360294 0.03612107
  0.07221299 0.05916972 0.06833777 0.06166303 0.06530877 0.10302629
  0.08327809 0.04777101 0.04464434 0.04320488 0.06043263 0.07127287
  0.04358247 0.04572369 0.07450921 0.07450921 0.0

In [13]:
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.utils import shuffle

class KNN:
    def __init__(self, k):
        self.Y_train = None
        self.X_train = None
        self.k = k
    
    def fit(self, X_train, Y_train):
        # Store the training data in sparse format if it isn't already
        self.X_train = csr_matrix(X_train) if not isinstance(X_train, csr_matrix) else X_train
        self.Y_train = Y_train
    
    def cosine_similarity(self, x, y):
        # Convert x to a sparse matrix if it isn't already
        x = csr_matrix(x) if not isinstance(x, csr_matrix) else x
        y = csr_matrix(y) if not isinstance(y, csr_matrix) else y

        # Compute the norms of each row vector in the sparse matrices
        norms_vector = np.sqrt(x.multiply(x).sum(axis=1).A1)  # Efficient norm calculation for sparse data
        norms_vectors = np.sqrt(y.multiply(y).sum(axis=1).A1)

        # Avoid division by zero by handling zero or near-zero norms
        norms_vector[norms_vector == 0] = 1e-10
        norms_vectors[norms_vectors == 0] = 1e-10

        # Compute the dot product between x and y using sparse matrix operations
        dot_product = y.dot(x.T).toarray()  # Convert to a dense array for cosine similarity calculation

        return dot_product / np.outer(norms_vectors, norms_vector)

    def predict(self, x):
        # Use cosine similarity to measure distances
        cosine_similarity = self.cosine_similarity(x, self.X_train)

        # Find k-nearest neighbors efficiently using argsort
        knn_indices = np.argsort(cosine_similarity.T, axis=1)[:, -self.k:]

        # Retrieve the labels for the k-nearest neighbors
        knn_labels = self.Y_train[knn_indices]

        # Predict the labels by finding the most common label among the neighbors
        predictions = np.array([np.argmax(np.bincount(np.clip(labels.astype(int), 0, None))) for labels in knn_labels])

        return predictions


In [14]:
from scipy import sparse
from sklearn.utils import shuffle

def cross_validation(predictions, y_test):
    true_positive = true_negative = false_positive = false_negative = 0    
    for t_label, p_label in zip(y_test, predictions):
        if t_label == 1 and p_label == 1:
            true_positive += 1
        elif t_label == 2 and p_label == 2:
            true_negative += 1
        elif t_label == 2 and p_label == 1:
            false_positive += 1
        elif t_label == 1 and p_label == 2:
            false_negative += 1
    return [true_positive, true_negative, false_positive, false_negative]

def k_fold_cross_validation(x, y, folds, k):
    accuracy_sum = 0

    # Shuffle the data before splitting into folds
    x, y = shuffle(x, y, random_state=42)
    fold_size = x.shape[0] // folds
    print("\nFold Size: " + str(fold_size))

    for i in range(folds):
        start_index = i * fold_size
        end_index = (i + 1) * fold_size if i < (folds - 1) else x.shape[0]

        # Split the data into training and validation sets using sparse slicing
        x_val_fold = x[start_index:end_index]
        x_train_fold = sparse.vstack([x[:start_index], x[end_index:]])

        y_val_fold = y[start_index:end_index]
        y_train_fold = np.concatenate([y[:start_index], y[end_index:]])

        # Train the k-NN classifier with the current fold's training data
        knn_classifier = KNN(k)
        knn_classifier.fit(x_train_fold, y_train_fold)

        # Predict the labels for the validation set
        predictions = knn_classifier.predict(x_val_fold)
        print(predictions)

        # Calculate the confusion matrix for the current fold
        confusion_matrix = cross_validation(predictions, y_val_fold)
        accuracy_score = (confusion_matrix[0] + confusion_matrix[1]) / len(y_val_fold)
        accuracy_sum += accuracy_score

        print(f"k: {k} ====== fold index: {i} ==== accuracy: {accuracy_score}")

    # Calculate the overall accuracy across all folds
    overall_accuracy = accuracy_sum / folds
    print("Overall Accuracy: " + str(overall_accuracy))
    return overall_accuracy


In [15]:
from sklearn.feature_selection import SelectKBest, chi2

#k_best = 2000  # Number of features to select
#selector = SelectKBest(chi2, k=k_best)
#X_train = selector.fit_transform(X_train, Y_train)
folds = 6
k_fold_cross_validation(X_train, Y_train, folds, k=191) # Randomly taking K as 7 for the base line model


Fold Size: 4166
[1 2 2 ... 2 2 1]
k: 191 ====== fold index: 0 ==== accuracy: 0.8101296207393183
[2 2 2 ... 1 1 1]
k: 191 ====== fold index: 1 ==== accuracy: 0.8202112337974076
[1 2 2 ... 2 2 2]
k: 191 ====== fold index: 2 ==== accuracy: 0.8206913106096976
[2 1 2 ... 2 2 1]
k: 191 ====== fold index: 3 ==== accuracy: 0.828852616418627
[1 1 2 ... 1 2 2]
k: 191 ====== fold index: 4 ==== accuracy: 0.8125300048007681
[1 2 1 ... 1 1 1]
k: 191 ====== fold index: 5 ==== accuracy: 0.8172661870503597
Overall Accuracy: 0.8182801622360296


0.8182801622360296

### Now lets Do Hyperparameter tuning inorder to find the best K neighbour

In [20]:
# best_accuracy = 0
# best_k = 0
# accuracy_map = {}

# # Test different k values from 10 to 400
# for k in range(10, 401):
#     accuracy = k_fold_cross_validation(X_train, Y_train, folds=6, k=k)
#     accuracy_map[k] = accuracy
#     if accuracy > best_accuracy:
#         best_accuracy = accuracy
#         best_k = k

# print(f"Best k value: {best_k} with accuracy: {best_accuracy}")


In [16]:
Test_file = "Test.txt"
preprocessed_test_data = []

with open(Test_file, 'r', encoding='utf-8') as file:
  for line in file:
    if line.strip():
        review_text = line.strip()
        if review_text.endswith("EOF"):
          review = review_text[:-3].strip()  
        review_text = preprocess_text(review)
        preprocessed_test_data.append(review_text)

In [17]:
preprocessed_test_data[0]

"low budget film set one location valley shielded effect radiation cast older man daughter handsome visitor couple tough buy gal drifter donkey radiation affected man interact effect nuclear blast added entity watching woman take bath gun get shot told child others murdered others drift away well movie harvey cormann 's first film show certain simplicity movie making avoid expensive set actor go curtain enter exit house ie studio location shot filmed hill near hollywood backdrop would say worth going way see interesting see movie human subject made 50"

In [18]:
X_test = tfidf_vectorizer.transform(preprocessed_test_data)
#X_test = selector.transform(X_test)
best_k_from_trained_model = 191

knn_classifier = KNN(k=best_k_from_trained_model)
knn_classifier.fit(X_train, np.array(Y_train))

predictions = knn_classifier.predict(X_test)

# Replace the label value 2 with -1, as this was done earlier in the training phase
predictions[predictions == 2] = -1
file_name = "predictions.txt"
# Save the predictions to a file with a timestamped name
with open(file_name, 'w+') as file:
    for prediction in predictions:
        file.write(str(prediction) + '\n')

print(f"Predictions written to file: {file_name}")

MemoryError: Unable to allocate 4.46 GiB for an array with shape (598308375,) and data type float64